recipe: default.v1
language: en

pipeline:
  - name: "SpacyNLP" 
    model: "en_core_web_trf"
  - name: "SpacyTokenizer"
  - name: "SpacyFeaturizer"
  - name: "SpacyEntityExtractor"
    dimensions: ["Person"]
  # - name: "RegexFeaturizer"
  - name: "LexicalSyntacticFeaturizer"
  - name: "CountVectorsFeaturizer"
  - name: "CountVectorsFeaturizer"
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: "DIETClassifier"
    epochs: 100
    learning_rate: 0.001
    batch_size: [8, 32]
    constrain_similarities: True
  # - name: "RegexEntityExtractor"  
  #   case_sensitive: False
  #   use_lookup_tables: True
  # - name: rasa_nlu_examples.extractors.FlashTextEntityExtractor
  #   case_sensitive: False
  #   path: data/lookups/first_name.txt
  #   entity_name: first_name
  #   encoding: 'utf8'
  # - name: rasa_nlu_examples.extractors.FlashTextEntityExtractor
  #   case_sensitive: False
  #   path: data//lookups/last_name_2.txt
  #   entity_name: last_name
  #   encoding: 'utf8'  
  # - name: "EntitySynonymMapper"
  # # - name: ResponseSelector
  # #   epochs: 100
  # #   retrieval_intent: faq
  - name: FallbackClassifier
    threshold: 0.7
    ambiguity_threshold: 0.1  

policies:
  - name: TEDPolicy
    max_history: 5
    epochs: 300
    batch_size: 50
    max_training_samples: 300
    constrain_similarities: True
  - name: MemoizationPolicy
  - name: RulePolicy
